Timbit87/Influintelligent

app/models/collaboration.rb, db/migrate/20240713075215_create_collaborations.rb, db/schema.rb, test/models/collaboration_test.rb
=> created collaboration model

app/models/application.rb, db/migrate/20240713080347_create_applications.rb, db/schema.rb, test/models/application_test.rb
=> added application model

db/migrate/20240713090301_rename_applications_to_submissions.rb, db/schema.rb
renamed Applications to Submissions
=> renamed applications to submissions

app/controllers/applications_controller.rb, app/controllers/collaborations_controller.rb, app/controllers/users_controller.rb, test/controllers/applications_controller_test.rb, test/controllers/collaborations_controller_test.rb, test/controllers/users_controller_test.rb
, we have to be careful because theres application and applications
=> added the controller files

app/controllers/brands_controller.rb, test/controllers/brands_controller_test.rb
Brands controller created.
Brand new and create methods defined.
Brand strong params defined.
=> Brands controller

app/controllers/users_controller.rb, app/views/influencers/edit.html.erb, app/views/influencers/index.html.erb, app/views/influencers/new.html.erb, app/views/influencers/show.html.erb
=> User controller

config/routes.rb
Created routes for brands and submissions
=> Routes done. Maybe

app/controllers/brands_controller.rb, app/controllers/collaborations_controller.rb
updated new brand and created collaboration controller
=> Collaboration creation

app/controllers/users_controller.rb, app/models/user.rb, db/schema.rb
=> define brand and influencer scope on user

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/brands_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/brands/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/seeds.rb
made some changes in brands controller, applications and user controller
=> Show brand

config/routes.rb
the route updated by Yann as Slack. 
Please check and confirm.
=> route updated by Yann

app/controllers/submissions_controller.rb
@StevenEReyes 
Hiya, I edited Submissions controller which
index = as a influencers, i can see all my submissions.
create = as a influencer, I can create my submission which is under collab page so nested.
set_collaboration = created with collab as create action is under collab page.
I didnt create submission_params cause when influencer submit submission, itll be on collab show page and it won't require any other items I guess.
Better to confirm about this part with TA but if it seems good, pls confirm and merge else pls feel free to edit on your own.
=> Submissions controller

app/views/submissions/index.html.erb
updated views submission index file.
Not sure if it would work to be honest as no record for collab and submission, didnt check on server yet.
if it looks ok, pls confirm. 
If not comment or edit please!
=> updated submissions index

db/seeds.rb
hello updated seeds with collab and submission.
Worked well in local but not sure with the latest master as many things have been changing. 
Can update seeds later aligning the latest master I think.
=> updated seeds for collab and submission

app/views/submissions/index.html.erb, db/schema.rb, db/seeds.rb
=> updated index file

app/models/collaboration.rb, app/models/user.rb
updated models with dependency to run seeds without errors
=> updated models

app/views/pages/home.html.erb, config/environments/development.rb, config/storage.yml
=> added cloudinary to active storage

app/controllers/submissions_controller.rb, app/views/collaborations/show.html.erb
=> placed submit button in 'a' tag

app/views/submissions/index.html.erb
its just fix for few min, sorry I should have done this morning.
=> updated index page submission

app/views/components/_collaboration_card.html.erb, app/views/components/_landing_card.html.erb, app/views/pages/home.html.erb, db/schema.rb
You were right Steven, should be uploaded for default
=> Remove cloudinary for default images

db/schema.rb, db/seeds.rb
=> added more seeds

app/views/collaborations/show.html.erb
change from collaboration.price to @collaboration.price
=> fixed number_to_currency collaboration.price argument on Collab Show

app/assets/stylesheets/pages/_index.scss, app/views/influencers/show.html.erb
added .capitalize to names
Also moved the profile to influencers/show because that's where the controller was searching
=> Dot capitalize

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tags.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/collaborations_controller.rb, app/models/collaboration.rb, app/views/collaborations/category.html.erb, app/views/collaborations/index.html.erb, app/views/collaborations/new.html.erb, app/views/collaborations/show.html.erb, app/views/components/_collaboration_card.html.erb, app/views/components/_landing_card.html.erb, config/routes.rb
tags for collaboration categories
=> category collaborations

app/controllers/users_controller.rb, app/views/brands/show.html.erb, app/views/components/_influencers_card.html.erb, app/views/influencers/show.html.erb, app/views/shared/_sidebar.html.erb, app/views/users/index.html.erb
Lots of placeholders and cards are ugly as sin, but all the linking works
=> Brands can now search for influencers, lots of placeholders

app/views/shared/_sidebar.html.erb
=> Changed influencer icon to search icon

app/controllers/submissions_controller.rb, app/views/brand/submissions/index.html.erb
Hello 
Added accept or decline button on brand submission page, I will try to make it more beautiful with css when  I will have a time... !
=> added accept or decline button on brand submission page

app/controllers/brand/submissions_controller.rb
take the line causing error out
=> take irrelevant line out not to cause error

app/assets/stylesheets/components/_banner_image.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/collaborations_controller.rb, app/models/collaboration.rb, app/views/collaborations/new.html.erb, app/views/collaborations/show.html.erb
added banner to collaborations
=> collaboration new form

app/views/brand/submissions/index.html.erb
updated button style for brand/submission page
=> updated approval button for submission page for brand

app/views/brand/submissions/index.html.erb
now brand can check the message from influencer on submission page
=> add column of message from influencer on submission page

app/controllers/submissions_controller.rb, app/views/submissions/index.html.erb, app/views/submissions/update.html.erb, config/routes.rb
=> added withdraw button on influencer submission page

app/views/components/_influencers_card.html.erb, app/views/influencers/show.html.erb
Profile pic works for influencers but not for brands?
Also card profile size not fixed yet. I failed at that. Will fix tomorrow morning as too hard into my Otokoume sours.
=> Profile pic appears on page, size of profile on card should be fixed

app/controllers/users_controller.rb, app/views/brands/show.html.erb, app/views/influencers/show.html.erb
Fixed profile images to relevant users
=> Fixed profile images

app/assets/stylesheets/components/_banner_image.scss, app/assets/stylesheets/components/_collaboration_card.scss, app/controllers/collaborations_controller.rb, app/views/collaborations/edit.html.erb, app/views/collaborations/index.html.erb, app/views/collaborations/show.html.erb, app/views/components/_collaboration_card.html.erb, config/routes.rb
as a brand i can edit my collaboration
=> edit my collaboration

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/brand/submissions_controller.rb, app/controllers/collaborations_controller.rb, app/controllers/pages_controller.rb, app/controllers/registrations_controller.rb, app/controllers/submissions_controller.rb, app/controllers/users_controller.rb, app/policies/application_policy.rb, app/policies/user_policy.rb, app/views/brands/show.html.erb, app/views/influencers/show.html.erb, config/application.rb, config/environment.rb, test/policies/user_policy_test.rb
logged in as chika, you can not edit cocacola profile.
logged in as cocacola, you can not edit chika's profile.
I made sure other tab also works fine.
=> added pundit for user model

app/views/collaborations/show.html.erb, db/schema.rb
Discard schema changes? I dunno
=> Fix dollar sign

app/views/brands/show.html.erb
=> updated review on brand profile page
